services:
  kafka:
    image: confluentinc/cp-kafka:7.8.3
    hostname: kafka
    ports:
      - "39092:9092"
      - "29092:29092"
    environment:
      KAFKA_KRAFT_MODE: 'true'
      CLUSTER_ID: '1L6g7nGhU-eAKfL--X25wo'
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LISTENERS: >
        PLAINTEXT_EXTERNAL://0.0.0.0:9092,
        PLAINTEXT_INTERNAL://0.0.0.0:29092,
        CONTROLLER://0.0.0.0:9093

      KAFKA_ADVERTISED_LISTENERS: >
        PLAINTEXT_EXTERNAL://${HOST_IP}:39092,
        PLAINTEXT_INTERNAL://kafka:29092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
        PLAINTEXT_EXTERNAL:PLAINTEXT,
        PLAINTEXT_INTERNAL:PLAINTEXT,
        CONTROLLER:PLAINTEXT

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs

    volumes:
      - kafka_data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "5000:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "Local Kafka"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:29092"
    depends_on:
      - kafka
volumes:
  kafka_data: