services:
  kafka:
    image: confluentinc/cp-kafka:7.8.3
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"    # para el backend (fuera de Docker)
      - "29092:29092"  # para Kafka UI (u otros contenedores)
    environment:
      # Activar modo KRaft (sin Zookeeper)
      KAFKA_KRAFT_MODE: 'true'

      # ID √∫nico del cl√∫ster
      CLUSTER_ID: '1L6g7nGhU-eAKfL--X25wo'

      # ID √∫nico del nodo (solo uno en este caso)
      KAFKA_NODE_ID: 1

      # Roles que cumple el nodo
      KAFKA_PROCESS_ROLES: broker,controller

      # Define el "quorum" de controladores (solo uno)
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

       # üîπ Listeners internos y externos
      KAFKA_LISTENERS: PLAINTEXT_INTERNAL://0.0.0.0:29092,PLAINTEXT_EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      
      # - "kafka:29092" para contenedores internos (UI)
      # - "localhost:9092" para el backend en el host
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://kafka:29092,PLAINTEXT_EXTERNAL://localhost:9092

      
      # Define qu√© listener usa el controlador
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # Indicar a kafka que lsitener usar para comunicarse consigo mismo o entre brokers
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL

      # Factores de replicaci√≥n internos m√≠nimos (solo 1 nodo)
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      # Carpeta interna de logs de Kafka
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs

    volumes:
      - kafka1_data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "5000:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "Local Kafka"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:29092"
    depends_on:
      - kafka

volumes:
  kafka1_data: